# makefile, con lib math.h
CC=gcc
CFLAGS=-Wall  -Wno-return-type -Wno-implicit-int -g -O -pedantic -Wformat=2 -Wextra -lm

main: main.o ../lib/procedure.array.o ../lib/function.array.o

../lib/procedure.array.o: ../lib/procedure.array.h:
../lib/function.array.o: ../lib/function.array.h:
